name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # 通过命令获取当前 version 信息, 存入环境变量 APP_VERSION
    - name: Generate App Version
      run: echo APP_VERSION=$(cat version.txt) >> $GITHUB_ENV
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile # Dockerfile 位置
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/paddleocr:latest,${{ secrets.DOCKERHUB_USERNAME }}/paddleocr:${{ env.APP_VERSION }}
    - name: Build the Docker image noavx
      uses: docker/build-push-action@v2
      with:
        context: .
        build-args: PADDLE_VER=${{ env.APP_VERSION }}
        file: ./Dockerfile-noavx # Dockerfile 位置
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/paddleocr:latest-noavx,${{ secrets.DOCKERHUB_USERNAME }}/paddleocr:${{ env.APP_VERSION }}-noavx
